sonar.projectKey=sire
sonar.projectName=SIRE - Sistema de Reservas
sonar.projectVersion=1.0

# Lenguaje principal
sonar.language=dart
sonar.dart.file.suffixes=.dart

# Fuentes y tests
sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*_test.dart
sonar.sourceEncoding=UTF-8

# Exclusiones (archivos generados por build_runner y Riverpod)
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**

# Cobertura (generada con: flutter test --coverage)
sonar.flutter.coverage.reportPaths=coverage/lcov.info

sonar.host.url=http://localhost:9000
