# 1 Usar una imagen base oficial y ligera de Node.js
FROM node:20-alpine

# 2 Instalar OpenSSL (Requisito indispensable para que Prisma funcione en Alpine Linux)
RUN apk add --no-cache openssl

# 3 Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# 4 Copiar solo los archivos de dependencias primero (aprovecha la caché de Docker)
COPY package*.json ./

# 5 Instalar todas las dependencias
RUN npm install

# 6 Copiar la carpeta de Prisma y generar el cliente de base de datos
COPY prisma ./prisma/
RUN npx prisma generate

# 7 Copiar el resto del código fuente del proyecto
COPY . .

# 8 Compilar el código TypeScript a JavaScript (ejecuta tu script "build")
RUN npm run build

# 9 Exponer el puerto en el que corre Fastify (ajusta el número si usas otro)
EXPOSE 3000

# 10 Comando para arrancar el servidor en producción
CMD ["npm", "run", "start"]