sonar.projectKey=test-backend
sonar.projectName=SIRE Backend
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9000
sonar.token=sqp_888abe7f0fdf2630704169f4454fe21ac9c59704

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**, dist/**, prisma/migrations/**, coverage/**