sonar.projectKey=Test_Backend
sonar.projectName=SIRE Backend
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9000
sonar.token="TOKEN AQUI"

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**, dist/**, prisma/migrations/**, coverage/**