# Identificación del proyecto
sonar.projectKey=Test
sonar.projectName=Test

# Conexión a tu Docker local
sonar.host.url=http://localhost:9000
sonar.token=sqp_2df8a787235e07bd30b822c985982ea00c16c31d

# Rutas de tu código fuente y tus tests
sonar.sources=src
sonar.tests=tests

# Configuraciones específicas para TypeScript y Node
sonar.language=ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusiones (Para que no evalúe código generado o librerías)
sonar.exclusions=node_modules/**, dist/**, prisma/**
sonar.test.inclusions=tests/**/*.test.ts